### ISSUE TITLE
HH:MM for Gravity Forms

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/HavensCreamery#1]
The HH:MM on this page: http://havenscreamery.com/events/

You should see this:
![screen shot 2017-02-12 at 2 54 32 pm](https://cloud.githubusercontent.com/assets/10511034/22865467/53c73390-f133-11e6-8045-183dbe3984ad.png)

Please style this properly so they are all on one line.

**Comment by nitubasra** [comment]
I have completed the fixes please review. I have worked on style.css under the food-drop-child theme.
