### ISSUE TITLE
Address Fields "Gravity Forms" Styling

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/HavensCreamery#3]
On this page: http://havenscreamery.com/employment/ the "Perm Address" fields are really messy / not aligned. Please fix this so it works well on both mobile & desktop.

![screen shot 2017-02-21 at 3 42 48 am](https://cloud.githubusercontent.com/assets/10511034/23157160/f0bb453c-f7e7-11e6-9fae-03e7ece3363d.png)

**Comment by nitubasra** [comment]
I have completed the fixes please review. I have worked on style.css under the food-drop-child theme.
