### ISSUE TITLE
Product Price is Hidden.

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/HavensCreamery#5]
As you can see here:
![screen shot 2017-03-05 at 2 42 12 pm](https://cloud.githubusercontent.com/assets/10511034/23590653/fe79ea38-01b1-11e7-997d-ed6585adb838.png)

The price is not showing because of code:

.woocommerce div.product p.price, .woocommerce div.product span.price {display: none;}

...but when i removed this from the styles.css it still is hidden.

**Comment by sgerritse** [comment]
It is happening on all products. 
1. http://havenscreamery.com/shop/event-packages/birthday-party-special-event-basic/
2. http://havenscreamery.com/shop/event-packages/birthday-party-special-event-premium/
3. http://havenscreamery.com/shop/event-packages/birthday-party-special-event-deluxe/

and on Shop / Store main page:
http://havenscreamery.com/shop/

**Comment by sumeena** [comment]
![heavenly price shop](https://cloud.githubusercontent.com/assets/3082046/23690554/8b626a8c-03e8-11e7-9026-afdaaf9133c3.png)
![heavenly price first](https://cloud.githubusercontent.com/assets/3082046/23690553/8b5fe80c-03e8-11e7-803c-57717b1c6b45.png)
price is showing at my end.
