### ISSUE TITLE
Fix Styling on "Cat" page

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/HavensCreamery#7]
As seen here: http://havenscreamery.com/cat/event-packages/

![screen shot 2017-03-05 at 3 14 25 pm](https://cloud.githubusercontent.com/assets/10511034/23590920/76c9a1e6-01b6-11e7-9dda-cda2405cf363.png)

Please fix on Desktop / Mobile

**Comment by sumeena** [comment]
done
