### ISSUE TITLE
Fix "Footer" padding / spacing?

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/HavensCreamery#9]
See at the bottom of this page: http://havenscreamery.com/ice-cream-flavors/

![screen shot 2017-03-05 at 4 41 03 pm](https://cloud.githubusercontent.com/assets/10511034/23591695/98ae404e-01c2-11e7-86cc-cbe16825a779.png)

Should be more like this: 

![screen shot 2017-03-05 at 4 41 03 pm](https://cloud.githubusercontent.com/assets/10511034/23591701/a6b6c760-01c2-11e7-96b6-c5fd39af2660.png)

**Comment by nitubasra** [comment]
I have updated the code on wordpress page
http://havenscreamery.com/wp-admin/post.php?post=71&action=edit
and fixed the issue. Please check
